pid /tmp/nginx.pid;
error_log /dev/stderr info;

events {}

http {
  include /etc/nginx/mime.types;
  access_log /dev/stdout;
  server {
    listen 80;
    server_name _;
    root /lzcapp/pkg/content/web;
    index index.html;

    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
