application:
  subdomain: gpt-image-playground
  routes:
    - /=http://web:80
services:
  web:
    image: registry.lazycat.cloud/nginx:1.27.3
    entrypoint: /bin/sh
    command: /lzcapp/pkg/content/start.sh
